[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true
	showCreativeTabNameInSearchbar = true
	disabledCreativeModeTabs = ["minecraft:op_blocks", "vanillabackport:vanilla_backport"]

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true
